package main;

public interface C {
    String BARBER_IS_SHAVING = "BARBER_IS_SHAVING";
    String BARBER_IS_SLEEPING = "BARBER_IS_SLEEPING";

    String WAITING_ROOM_IS_FULL = "WAITING_ROOM_IS_FULL";
    String WAITING_ROOM_HAS_FREE_PLACES = "WAITING_ROOM_IS_HAS_FREE_PLACES";

    String SLEEPING_PLACE_IS_EMPTY = "SLEEPING_PLACE_IS_EMPTY";
    String SLEEPING_PLACE_HAS_BARBER = "SLEEPING_PLACE_HAS_BARBER";

    String SHAVING_PLACE_HAS_CUSTOMER = "SHAVING_PLACE_HAS_CUSTOMER";
    String SHAVING_PLACE_IS_EMPTY = "SHAVING_PLACE_IS_EMPTY";

}
